name: publish-pixark
on: [push]
jobs:
    publish-pixark:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
                uses: actions/checkout@v4
            
            - name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                    
            - name: Build the hello-docker Docker image
                run: |
                   docker build ./pixark --tag ghcr.io/lucanero/pixark:latest
                   docker push ghcr.io/lucanero/pixark:latest
